#!/bin/bash

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║   Twitter Auto-Monitor - Full Automation Setup           ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "This will set up AUTOMATIC Twitter monitoring that:"
echo "  ✓ Monitors @GBA_office and @ICCCBengaluru every hour"
echo "  ✓ Automatically posts supportive replies"
echo "  ✓ Respects Twitter API rate limits (never exceeds)"
echo "  ✓ Runs 24/7 without manual intervention"
echo ""

# Check if already set up
if [ -f .data/rate-limits.json ]; then
    echo -e "${YELLOW}⚠️  Rate limit tracker already exists${NC}"
    echo "Current status:"
    cat .data/rate-limits.json | grep -A 2 "mentionTimeline" | head -3
    echo ""
fi

echo "═══════════════════════════════════════════════════════════"
echo "OPTION 1: Manual Testing (Run Once)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Test the automation manually:"
echo "  curl http://localhost:3000/api/cron/monitor-twitter"
echo ""
echo "This will:"
echo "  1. Check rate limits"
echo "  2. Fetch recent complaints"
echo "  3. Post replies (if within limits)"
echo "  4. Show results"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "OPTION 2: Hourly Automation (Cron Job)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Set up cron job to run every hour:"
echo ""
echo "1. Edit crontab:"
echo "   crontab -e"
echo ""
echo "2. Add this line:"
echo "   0 * * * * curl http://localhost:3000/api/cron/monitor-twitter >> /tmp/twitter-monitor.log 2>&1"
echo ""
echo "3. Save and exit"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "OPTION 3: Systemd Service (Always Running)"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Create systemd timer for production:"
echo ""
echo "1. Create service file: /etc/systemd/system/twitter-monitor.service"
echo "2. Create timer file: /etc/systemd/system/twitter-monitor.timer"
echo "3. Enable: sudo systemctl enable twitter-monitor.timer"
echo "4. Start: sudo systemctl start twitter-monitor.timer"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "Rate Limit Safety"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Your setup uses:"
echo "  • 2 API calls per hour (2 handles)"
echo "  • 48 calls per day"
echo "  • Twitter limit: 96 calls per day"
echo "  • Safety margin: 50% ✓"
echo ""
echo "Max replies per run: 5"
echo "Delay between replies: 2 minutes"
echo ""
echo "The system will AUTOMATICALLY:"
echo "  ✓ Stop if rate limit reached"
echo "  ✓ Wait until limit resets"
echo "  ✓ Resume monitoring"
echo "  ✓ Never exceed limits"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "Quick Start Command"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo -e "${GREEN}To test NOW (posts real replies):${NC}"
echo ""
echo "  curl http://localhost:3000/api/cron/monitor-twitter"
echo ""
echo -e "${YELLOW}⚠️  This will POST REAL REPLIES to Twitter!${NC}"
echo ""

echo "═══════════════════════════════════════════════════════════"
echo "Monitoring & Logs"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Check rate limit status:"
echo "  cat .data/rate-limits.json"
echo ""
echo "Check processed tweets:"
echo "  cat .data/processed-tweets.json"
echo ""
echo "View logs:"
echo "  tail -f /tmp/twitter-monitor.log"
echo ""

echo "✅ Setup complete!"
echo ""
echo "Next steps:"
echo "  1. Start your dev server: pnpm dev"
echo "  2. Test manually: curl http://localhost:3000/api/cron/monitor-twitter"
echo "  3. Set up cron for automation"
echo ""
